import type { GlossaryTerm } from './types'

/**
 * Glossary — drone-cybersecurity focused definitions.
 * Each term: what it is, why it matters for drones, a short example.
 */
export const glossary: GlossaryTerm[] = [
  {
    term: 'UAV',
    acronym: 'Unmanned Aerial Vehicle',
    definition: 'Aeronave sin tripulación a bordo, controlada por sistemas autónomos o remotos.',
    whyItMatters: 'Es el activo físico que proteges. Comprometer un UAV implica riesgo material, no solo de datos.',
    example: 'Un cuadricóptero DJI o un fixed-wing PX4.',
    category: 'drone',
  },
  {
    term: 'UAS',
    acronym: 'Unmanned Aircraft System',
    definition: 'El sistema completo: UAV + estación de control + enlace de comunicaciones + personal.',
    whyItMatters: 'Recordar que la seguridad cubre TODO el sistema, no solo el drone que vuela.',
    example: 'Drone + GCS en portátil + radio SiK 915 MHz.',
    category: 'drone',
  },
  {
    term: 'Flight Controller',
    definition: 'Microcontrolador en tiempo real que estabiliza y controla el vuelo del UAV.',
    whyItMatters: 'Ejecuta firmware (PX4/ArduPilot/Betaflight). Un compromiso aquí = control total.',
    example: 'Pixhawk con ArduPilot, recebiendo órdenes por MAVLink.',
    category: 'drone',
  },
  {
    term: 'Companion Computer',
    definition: 'Ordenador Linux a bordo del drone que ejecuta lógica de misión de alto nivel.',
    whyItMatters: 'Expone SSH, APIs y servicios. Es el host más "normal" desde una perspectiva ofensiva.',
    example: 'Raspberry Pi 4 ejecutando ROS + MAVROS.',
    category: 'drone',
  },
  {
    term: 'GCS',
    acronym: 'Ground Control Station',
    definition: 'Software en tierra que pilota y monitorea el UAV.',
    whyItMatters: 'Si se compromete, el atacante controla el drone entero. Suele ser el eslabón débil.',
    example: 'QGroundControl en un portátil del piloto.',
    category: 'drone',
  },
  {
    term: 'MAVLink',
    acronym: 'Micro Air Vehicle Link',
    definition: 'Protocolo binario ligero de telemetría y control para UAVs. Usa UDP/TCP/serial.',
    whyItMatters: 'Por defecto sin cifrar ni autenticar. Base de casi todo el tráfico drone → GCS.',
    example: 'Mensaje HEARTBEAT (ID 0) enviado cada 1 Hz.',
    category: 'drone',
  },
  {
    term: 'Telemetry',
    definition: 'Datos que el drone envía al suelo: posición, batería, modo, actitud.',
    whyItMatters: 'Su exposición filtra operaciones y ubicaciones. Suele ir sin cifrar.',
    example: 'Stream UDP 14550 con mensajes MAVLink ATTITUDE, GPS_RAW_INT.',
    category: 'drone',
  },
  {
    term: 'Endpoint',
    definition: 'Punto de comunicación al que se puede dirigir un mensaje: URL HTTP, socket UDP, etc.',
    whyItMatters: 'Cada endpoint es una superficie de ataque potencial. Enumerarlos es paso 1.',
    example: 'GET /api/drone/status o udp://10.10.10.10:14550.',
    category: 'web',
  },
  {
    term: 'Socket',
    definition: 'Extremo de un canal de comunicación bidireccional (IP:puerto, protocolo).',
    whyItMatters: 'Los servicios del companion (telemetría, API, SSH) se exponen como sockets.',
    example: '10.10.10.10:14550/udp para MAVLink.',
    category: 'network',
  },
  {
    term: 'Payload',
    definition: 'En redes: los datos transportados en un paquete (excluyendo headers). En drones: carga útil física.',
    whyItMatters: 'En capturas, el payload revela comandos reales. Distingue contexto red vs. físico.',
    example: 'Payload MAVLink: bytes del mensaje HEARTBEAT; payload físico: cámara/gimbal.',
    category: 'network',
  },
  {
    term: 'Firmware',
    definition: 'Software de bajo nivel que controla un hardware embebido (flight controller, módulo radio).',
    whyItMatters: 'Si se modifica (tampering), todo el sistema es sospechoso de raíz. Análisis con binwalk/Ghidra.',
    example: 'fmuv3.bin de PX4 o un .fw de DJI.',
    category: 'binary',
  },
  {
    term: 'SSID',
    acronym: 'Service Set Identifier',
    definition: 'Nombre legible de una red Wi-Fi.',
    whyItMatters: 'Drones con Wi-Fi exponen SSID predecibles (ej. "Drone-XXXX") que facilitan el descubrimiento.',
    example: 'Mavic-2A7F1C, AR.Drone-123456.',
    category: 'wireless',
  },
  {
    term: 'BSSID',
    acronym: 'Basic Service Set Identifier',
    definition: 'Dirección MAC del punto de acceso Wi-Fi.',
    whyItMatters: 'Identifica unívocamente al AP del drone aunque cambie el SSID. Base de captura 802.11.',
    example: '00:1A:2B:3C:4D:5E.',
    category: 'wireless',
  },
  {
    term: 'WPA2',
    acronym: 'Wi-Fi Protected Access 2',
    definition: 'Estándar de cifrado Wi-Fi basado en CCMP/AES y handshake de 4 vías.',
    whyItMatters: 'Drones antiguos usan WEP o WPA débil. Capturar el handshake permite offline cracking.',
    example: 'Handshake EAPOL capturado con airodump-ng.',
    category: 'wireless',
  },
  {
    term: 'WPA3',
    acronym: 'Wi-Fi Protected Access 3',
    definition: 'Sucesor de WPA2 con SAE (Simultaneous Authentication of Equals), resistente a offline cracking.',
    whyItMatters: 'Mitiga ataques clásicos de diccionario. Drones modernos deberían migrar.',
    example: 'SAE handshake en lugar de PSK 4-way.',
    category: 'wireless',
  },
  {
    term: 'PMF',
    acronym: 'Protected Management Frames',
    definition: 'Cifrado de frames de gestión 802.11 (deauth, disassoc) con WPA2/WPA3.',
    whyItMatters: 'Sin PMF, los ataques de deauth son triviales. Clave para hardening Wi-Fi de drones.',
    example: '802.11w habilitado en el AP del drone.',
    category: 'wireless',
  },
  {
    term: 'AP',
    acronym: 'Access Point',
    definition: 'Dispositivo que crea una red Wi-Fi a la que las stations se asocian.',
    whyItMatters: 'Muchos drones actúan como AP propio. Su config (canal, cifrado) define la superficie wireless.',
    example: 'El drone crea AP "Drone-WiFi", la app móvil se asocia.',
    category: 'wireless',
  },
  {
    term: 'RTSP',
    acronym: 'Real Time Streaming Protocol',
    definition: 'Protocolo de control para streams multimedia (inicia/para un stream de video).',
    whyItMatters: 'Las cámaras de drones suelen servir video por RTSP sin auth. Punto de exposición de video.',
    example: 'rtsp://10.10.10.10:8554/live',
    category: 'drone',
  },
  {
    term: 'UDP',
    acronym: 'User Datagram Protocol',
    definition: 'Protocolo de transporte sin conexión, sin garantías de entrega.',
    whyItMatters: 'MAVLink y telemetría suelen ir por UDP (baja latencia). Sin handshake → fácil spoofing.',
    example: 'Paquete UDP 14550 con HEARTBEAT.',
    category: 'network',
  },
  {
    term: 'TCP',
    acronym: 'Transmission Control Protocol',
    definition: 'Protocolo de transporte orientado a conexión, confiable y ordenado.',
    whyItMatters: 'APIs HTTP del drone usan TCP. Permite seguir streams, pero es más pesado.',
    example: 'Conexión TCP 80 al /api/drone/status.',
    category: 'network',
  },
  {
    term: 'API',
    acronym: 'Application Programming Interface',
    definition: 'Conjunto de endpoints y contratos para que programas se comuniquen.',
    whyItMatters: 'Las APIs REST del drone son superficie clásica: IDOR, auth bypass, SSRF, inyección.',
    example: 'POST /api/drone/lab-command con JSON.',
    category: 'web',
  },
  {
    term: 'IDOR',
    acronym: 'Insecure Direct Object Reference',
    definition: 'Vulnerabilidad donde un objeto se accede por ID sin verificación de autorización.',
    whyItMatters: 'Cambiando /api/drone/1/status a /api/drone/2/status a veces se ve el drone ajeno.',
    example: 'GET /api/drone/2/config sin ser dueño del drone 2.',
    category: 'web',
  },
  {
    term: 'JWT',
    acronym: 'JSON Web Token',
    definition: 'Token firmado (y opcionalmente cifrado) para autenticación stateless.',
    whyItMatters: 'Las APIs de drones usan JWT. Errores comunes: alg=none, secret débil, sin expiración.',
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
    category: 'web',
  },
  {
    term: 'RBAC',
    acronym: 'Role-Based Access Control',
    definition: 'Modelo de autorización donde los permisos se asignan a roles, no a usuarios individuales.',
    whyItMatters: 'Un drone bien diseñado separa roles piloto/observador/admin. Sin RBAC, sobrepermisos.',
    example: 'rol pilot → TAKEOFF/LAND; rol viewer → solo GET status.',
    category: 'security',
  },
  {
    term: 'STRIDE',
    definition: 'Modelo de amenazas de Microsoft: Spoofing, Tampering, Repudiation, Info disclosure, DoS, EoP.',
    whyItMatters: 'Framework estándar para threat-modeling de UAVs componente por componente.',
    example: 'Jamming = DoS; replay de comando = Tampering.',
    category: 'security',
  },
  {
    term: 'CRC',
    acronym: 'Cyclic Redundancy Check',
    definition: 'Suma de verificación para detectar corrupción de datos, no manipulación maliciosa.',
    whyItMatters: 'MAVLink usa CRC. Muchos creen que CRC = seguridad; NO protege contra inyección intencionada.',
    example: 'CRC-16/MCR al final de cada mensaje MAVLink v2.',
    category: 'security',
  },
  {
    term: 'Secure Boot',
    definition: 'Mecanismo que verifica la firma del firmware antes de ejecutarlo.',
    whyItMatters: 'Clave para defender flight controllers y companions contra firmware tampering.',
    example: 'U-Boot verifica firma ECDSA del kernel antes de boot.',
    category: 'security',
  },
  {
    term: 'Replay Attack',
    definition: 'Reenvío de un mensaje previamente capturado para engañar al receptor.',
    whyItMatters: 'MAVLink sin nonces/timestamps firmados es vulnerable a replay de comandos.',
    example: 'Recapturar y reenviar un COMMAND_LONG TAKEOFF.',
    category: 'security',
  },
  {
    term: 'Jamming',
    definition: 'Saturar un canal de radio con ruido para denegar el enlace.',
    whyItMatters: 'Ataque DoS clásico contra drones. Mitigación: frecuencia salto, failsafe, detección RSSI.',
    example: 'Ruido en 2.4 GHz que rompe el enlace drone↔GCS.',
    category: 'wireless',
  },
]
