import type { Tool } from './types'

/**
 * Toolbox — reference catalog of cybersecurity tools relevant to drone labs.
 * Each entry is intentionally concise; deep usage is taught inside modules.
 */
export const tools: Tool[] = [
  {
    id: 'wireshark',
    name: 'Wireshark',
    category: 'capture',
    level: 'beginner',
    description: 'Analizador gráfico de paquetes. El estándar de facto para inspeccionar tráfico de red.',
    useCase: 'Capturar y diseccionar tráfico del drone, seguir streams TCP/UDP, filtrar protocolos.',
    icon: 'Fish',
    commands: [
      { cmd: 'wireshark -k -i eth0', desc: 'Abrir captura en vivo en eth0' },
      { cmd: 'tshark -i eth0 -f "udp port 14550"', desc: 'Captura MAVLink en CLI' },
      { cmd: 'display filter: mavlink', desc: 'Filtrar paquetes MAVLink' },
      { cmd: 'Follow → UDP Stream', desc: 'Seguir un flujo de telemetría' },
    ],
    commonMistakes: [
      'Capturar en modo promíscuo sin permisos (root/cap_net_raw)',
      'Olvidar que Wireshark no descifra WPA2 sin handshake previo',
    ],
    relatedLab: 'lab-05-capture-the-drone',
  },
  {
    id: 'tcpdump',
    name: 'tcpdump',
    category: 'capture',
    level: 'beginner',
    description: 'Capturador de paquetes en línea de comandos. Ideal para servers y scripting.',
    useCase: 'Capturar tráfico a .pcap para analizar luego en Wireshark, filtrar en vivo.',
    icon: 'Terminal',
    commands: [
      { cmd: 'tcpdump -i eth0 -nn', desc: 'Captura numérica sin DNS' },
      { cmd: 'tcpdump -i eth0 host 10.10.10.10', desc: 'Solo tráfico del drone' },
      { cmd: 'tcpdump -i eth0 -w drone.pcap', desc: 'Guardar a pcap' },
      { cmd: 'tcpdump -nn -r drone.pcap', desc: 'Leer pcap guardado' },
    ],
    commonMistakes: ['Olvidar -nn (resolución DNS lenta)', 'No usar -w para análisis posterior'],
    relatedLab: 'lab-06-tcpdump',
  },
  {
    id: 'nmap',
    name: 'Nmap',
    category: 'network',
    level: 'beginner',
    description: 'Escáner de redes. Descubre hosts, puertos, servicios y versiones.',
    useCase: 'Encontrar el drone en la red, enumerar puertos de telemetría/API.',
    icon: 'Radar',
    commands: [
      { cmd: 'nmap -sn 10.10.10.0/24', desc: 'Ping sweep / descubrir hosts' },
      { cmd: 'nmap -sV -sC 10.10.10.10', desc: 'Versiones + scripts default' },
      { cmd: 'nmap -sU --top-ports 50 10.10.10.10', desc: 'Top puertos UDP' },
      { cmd: 'nmap -p- 10.10.10.10', desc: 'Todos los puertos TCP' },
    ],
    commonMistakes: ['UDP scan es lento, no escanear -p- UDP', 'Olvidar que -sV necesita root'],
    relatedLab: 'lab-08-find-the-drone',
  },
  {
    id: 'aircrack-ng',
    name: 'Aircrack-ng',
    category: 'wireless',
    level: 'intermediate',
    description: 'Suite completa para auditoría de redes Wi-Fi 802.11.',
    useCase: 'Capturar handshakes WPA2, deauth, descifrar tráfico en labs de entrenamiento.',
    icon: 'Wifi',
    commands: [
      { cmd: 'airmon-ng start wlan0', desc: 'Modo monitor' },
      { cmd: 'airodump-ng wlan0mon', desc: 'Descubrir APs' },
      { cmd: 'aireplay-ng -0 5 -a <BSSID> wlan0mon', desc: 'Deauth (lab propio)' },
      { cmd: 'aircrack-ng -w wordlist.cap capture.cap', desc: 'Crack WPA2' },
    ],
    commonMistakes: [
      'Usar modo monitor sin permisos legales',
      'Olvidar airmon-ng check kill (interfiere NetworkManager)',
    ],
    relatedLab: 'lab-15-virtual-wifi-lab',
  },
  {
    id: 'iw',
    name: 'iw',
    category: 'wireless',
    level: 'intermediate',
    description: 'Herramienta nl80211 para configurar dispositivos Wi-Fi en Linux.',
    useCase: 'Listar interfaces, cambiar canal, inspeccionar capacidades de la tarjeta.',
    icon: 'Radio',
    commands: [
      { cmd: 'iw dev', desc: 'Listar interfaces Wi-Fi' },
      { cmd: 'iw list', desc: 'Capacidades de la tarjeta' },
      { cmd: 'iw dev wlan0 set channel 6', desc: 'Cambiar canal' },
      { cmd: 'iw dev wlan0 link', desc: 'Estado del enlace' },
    ],
    relatedLab: 'lab-15-virtual-wifi-lab',
  },
  {
    id: 'ip',
    name: 'ip',
    category: 'network',
    level: 'beginner',
    description: 'Sucesor moderno de ifconfig/route. Gestiona interfaces, rutas y vecinos.',
    useCase: 'Inspeccionar y configurar la pila de red del companion computer.',
    icon: 'Network',
    commands: [
      { cmd: 'ip addr', desc: 'Direcciones de interfaces' },
      { cmd: 'ip route', desc: 'Tabla de rutas' },
      { cmd: 'ip neigh', desc: 'Caché ARP' },
      { cmd: 'ip -s link', desc: 'Estadísticas de interfaces' },
    ],
    relatedLab: 'lab-01-linux-basics',
  },
  {
    id: 'ss',
    name: 'ss',
    category: 'network',
    level: 'beginner',
    description: 'Sustituto de netstat. Lista sockets y conexiones.',
    useCase: 'Ver qué puertos escucha el companion computer (telemetría, API, SSH).',
    icon: 'Plug',
    commands: [
      { cmd: 'ss -tulpn', desc: 'TCP+UDP en escucha, con PID' },
      { cmd: 'ss -tan state established', desc: 'Conexiones establecidas' },
      { cmd: 'ss -s', desc: 'Resumen de sockets' },
    ],
    relatedLab: 'lab-01-linux-basics',
  },
  {
    id: 'netcat',
    name: 'Netcat (nc)',
    category: 'network',
    level: 'beginner',
    description: 'El "navaja suiza" de TCP/IP. Lee/escribe cualquier socket.',
    useCase: 'Banner grabbing, probar puertos de telemetría, recibir conexiones.',
    icon: 'Wrench',
    commands: [
      { cmd: 'nc -zv 10.10.10.10 80', desc: 'Probar puerto TCP' },
      { cmd: 'nc -u 10.10.10.10 14550', desc: 'Hablar MAVLink UDP' },
      { cmd: 'nc -lvnp 4444', desc: 'Escuchar en 4444' },
    ],
    commonMistakes: ['Olvidar -u para UDP', 'No usar -n para evitar DNS lento'],
    relatedLab: 'lab-08-find-the-drone',
  },
  {
    id: 'socat',
    name: 'socat',
    category: 'network',
    level: 'intermediate',
    description: 'Relé bidireccional entre canales de datos (TCP, UDP, files, pipes).',
    useCase: 'Puentes entre protocolos, redirigir telemetría, debug de sockets.',
    icon: 'Shuffle',
    commands: [
      { cmd: 'socat TCP-LISTEN:8080,fork TCP:10.10.10.10:80', desc: 'Proxy TCP' },
      { cmd: 'socat UDP-RECV:14550 -', desc: 'Recibir MAVLink a stdout' },
    ],
    relatedLab: 'lab-13-mavlink',
  },
  {
    id: 'curl',
    name: 'curl',
    category: 'web',
    level: 'beginner',
    description: 'Cliente HTTP/S y mucho más. Fundamental para APIs de drones.',
    useCase: 'Consultar la API REST del drone, probar auth, inspeccionar headers.',
    icon: 'Download',
    commands: [
      { cmd: 'curl http://10.10.10.10/api/drone/status', desc: 'GET simple' },
      { cmd: 'curl -i -H "Authorization: Bearer X" URL', desc: 'Con header de auth' },
      { cmd: 'curl -X POST -d \'{"cmd":"TAKEOFF"}\' URL', desc: 'POST JSON' },
      { cmd: 'curl -s URL | jq .', desc: 'Formatear JSON' },
    ],
    relatedLab: 'lab-10-api-security',
  },
  {
    id: 'jq',
    name: 'jq',
    category: 'utility',
    level: 'beginner',
    description: 'Procesador de JSON en línea de comandos.',
    useCase: 'Filtrar y formatear respuestas de la API del drone.',
    icon: 'Braces',
    commands: [
      { cmd: 'echo \'{"a":1}\' | jq .', desc: 'Pretty print' },
      { cmd: 'jq ".battery" status.json', desc: 'Extraer campo' },
      { cmd: 'jq ".[]" array.json', desc: 'Iterar array' },
    ],
    relatedLab: 'lab-10-api-security',
  },
  {
    id: 'burpsuite',
    name: 'Burp Suite',
    category: 'web',
    level: 'intermediate',
    description: 'Proxy interceptador para web/API security. Estándar profesional.',
    useCase: 'Interceptar y repetir peticiones a la API del drone, encontrar auth bypass.',
    icon: 'Bug',
    commands: [
      { cmd: 'Proxy → Intercept → On', desc: 'Capturar requests' },
      { cmd: 'Repeater', desc: 'Reenviar modificando' },
      { cmd: 'Intruder', desc: 'Fuzzing de parámetros' },
    ],
    commonMistakes: ['Olvidar configurar el certificado CA en el navegador HTTPS'],
    relatedLab: 'lab-11-request-capture',
  },
  {
    id: 'mitmproxy',
    name: 'mitmproxy',
    category: 'web',
    level: 'intermediate',
    description: 'Proxy HTTP/HTTPS programable en Python. Alternativa open-source a Burp.',
    useCase: 'Automatizar captura/modificación de tráfico API del drone.',
    icon: 'Filter',
    commands: [
      { cmd: 'mitmproxy -p 8080', desc: 'Proxy interactivo' },
      { cmd: 'mitmdump -w out.mitm', desc: 'Guarda todo a archivo' },
    ],
    relatedLab: 'lab-11-request-capture',
  },
  {
    id: 'binwalk',
    name: 'binwalk',
    category: 'binary',
    level: 'intermediate',
    description: 'Analiza y extrae firmware embebido. Encuentra filesystems y firmas.',
    useCase: 'Diseccionar imágenes de firmware de drones, extraer filesystems squashfs.',
    icon: 'Package',
    commands: [
      { cmd: 'binwalk firmware.bin', desc: 'Escaneo de firmas' },
      { cmd: 'binwalk -e firmware.bin', desc: 'Extraer embebidos' },
      { cmd: 'binwalk -A firmware.bin', desc: 'Opcodes (entropy)' },
    ],
    relatedLab: 'lab-17-firmware',
  },
  {
    id: 'ghidra',
    name: 'Ghidra',
    category: 'binary',
    level: 'advanced',
    description: 'Suite de ingeniería inversa de la NSA. Decompilador + análisis.',
    useCase: 'Revertir binarios del companion computer, encontrar backdoors en firmware.',
    icon: 'Binary',
    commands: [
      { cmd: 'File → Import Binary', desc: 'Cargar ELF' },
      { cmd: 'Analysis → Auto Analyze', desc: 'Análisis automático' },
      { cmd: 'Decompiler (F3)', desc: 'Pseudocódigo C' },
    ],
    relatedLab: 'lab-18-reverse-engineering',
  },
  {
    id: 'radare2',
    name: 'radare2',
    category: 'binary',
    level: 'advanced',
    description: 'Framework de RE en CLI. Rápido para scripting y análisis puntual.',
    useCase: 'Inspeccionar ELF del drone desde terminal, encontrar strings y funciones.',
    icon: 'SquareTerminal',
    commands: [
      { cmd: 'r2 -A binary', desc: 'Abrir y analizar' },
      { cmd: 'aaa; afl', desc: 'Listar funciones' },
      { cmd: 'iz', desc: 'Strings en .data' },
      { cmd: 'pdf @ main', desc: 'Decompilar main' },
    ],
    relatedLab: 'lab-18-reverse-engineering',
  },
  {
    id: 'strings',
    name: 'strings',
    category: 'binary',
    level: 'beginner',
    description: 'Extrae cadenas imprimibles de binarios.',
    useCase: 'Encontrar credenciales, URLs y mensajes en firmware de drones.',
    icon: 'Type',
    commands: [
      { cmd: 'strings -n 8 firmware.bin', desc: 'Cadenas ≥ 8 chars' },
      { cmd: 'strings firmware.bin | grep -i pass', desc: 'Buscar passwords' },
    ],
    relatedLab: 'lab-17-firmware',
  },
  {
    id: 'xxd',
    name: 'xxd / hexdump',
    category: 'binary',
    level: 'beginner',
    description: 'Visores hexadecimales de archivos.',
    useCase: 'Inspeccionar bytes de paquetes, headers de firmware, MAVLink crudo.',
    icon: 'Hexagon',
    commands: [
      { cmd: 'xxd file.bin', desc: 'Hex dump' },
      { cmd: 'xxd -l 64 file.bin', desc: 'Primeros 64 bytes' },
      { cmd: 'hexdump -C file.bin', desc: 'Con ASCII lateral' },
    ],
    relatedLab: 'lab-04-packets',
  },
  {
    id: 'objdump',
    name: 'objdump',
    category: 'binary',
    level: 'intermediate',
    description: 'Desensamblador de binarios ELF del toolchain GNU.',
    useCase: 'Ver secciones, símbolos y código asm de binarios del drone.',
    icon: 'FileCode',
    commands: [
      { cmd: 'objdump -d binary', desc: 'Desensamblar' },
      { cmd: 'objdump -t binary', desc: 'Tabla de símbolos' },
      { cmd: 'objdump -h binary', desc: 'Secciones' },
    ],
    relatedLab: 'lab-18-reverse-engineering',
  },
  {
    id: 'readelf',
    name: 'readelf',
    category: 'binary',
    level: 'intermediate',
    description: 'Inspector de headers ELF.',
    useCase: 'Verificar arquitectura, entry point, secciones de binarios del companion.',
    icon: 'FileSearch',
    commands: [
      { cmd: 'readelf -h binary', desc: 'Header ELF' },
      { cmd: 'readelf -S binary', desc: 'Secciones' },
      { cmd: 'readelf -d binary', desc: 'Dependencias dinámicas' },
    ],
    relatedLab: 'lab-18-reverse-engineering',
  },
  {
    id: 'ping',
    name: 'ping',
    category: 'network',
    level: 'beginner',
    description: 'ICMP echo. Verifica reachability y latencia.',
    useCase: 'Confirmar que el drone virtual responde antes de enumerar.',
    icon: 'Activity',
    commands: [
      { cmd: 'ping -c 3 10.10.10.10', desc: '3 paquetes y para' },
      { cmd: 'ping -i 0.5 host', desc: 'Intervalo rápido' },
    ],
    relatedLab: 'lab-08-find-the-drone',
  },
  {
    id: 'dig',
    name: 'dig',
    category: 'network',
    level: 'beginner',
    description: 'Consulta DNS flexible.',
    useCase: 'Resolver drone-lab.local, verificar registros del laboratorio.',
    icon: 'Search',
    commands: [
      { cmd: 'dig drone-lab.local', desc: 'Resolver A' },
      { cmd: 'dig +short MX example.com', desc: 'Solo respuesta' },
      { cmd: 'dig @8.8.8.8 example.com', desc: 'Servidor específico' },
    ],
    relatedLab: 'lab-02-networking',
  },
]
