import type { ContentModule } from '../types'

/**
 * Stub modules (04–27).
 *
 * These are intentionally "coming-soon": they expose the full outline
 * (objectives, planned lessons, tools) so the platform feels complete and
 * the student knows what's coming, but the lessons themselves are empty.
 * They are filled in progressively in later phases.
 */

function stub(
  partial: Omit<
    ContentModule,
    'status' | 'lessons' | 'labs' | 'outcomes'
  > & {
    outcomes?: string[]
    plannedLessons?: { title: string; duration: string }[]
  },
): ContentModule {
  const { plannedLessons, ...rest } = partial
  return {
    ...rest,
    status: 'coming-soon',
    lessons:
      plannedLessons?.map((l, i) => ({
        id: `${rest.id}-l${i + 1}`,
        moduleId: rest.id,
        title: l.title,
        slug: l.title
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/(^-|-$)/g, ''),
        duration: l.duration,
        difficulty: rest.difficulty,
        summary: 'Lección planificada para una fase posterior.',
        objectives: [],
        sections: [
          {
            id: 'placeholder',
            type: 'callout',
            variant: 'info',
            title: 'Próximamente',
            content: `Esta lección forma parte de "${rest.title}" y se desarrolla en una fase posterior del roadmap. Ya puedes explorar los módulos disponibles en Foundation.`,
          },
        ],
      })) ?? [],
    labs: [],
    outcomes: rest.outcomes ?? [],
  }
}

export const stubModules: ContentModule[] = [
  stub({
    id: '04-packets',
    number: '04',
    title: 'Packets',
    subtitle: 'Anatomía de un paquete de red',
    slug: 'packets',
    group: 'packets',
    difficulty: 'beginner',
    estimatedTime: '1.5 h',
    prerequisites: ['02-networking'],
    description:
      'El corazón técnico del curso: qué es una petición, qué hay dentro de un paquete, cómo se construye capa por capa y cómo se inspecciona.',
    icon: 'Package',
    outcomes: [
      'Diseccionar un paquete en sus capas Ethernet/IP/UDP/Payload',
      'Reconocer campos clave en cada header',
      'Leer un hex dump básico',
    ],
    plannedLessons: [
      { title: '¿Qué es un paquete?', duration: '10 min' },
      { title: 'Frame Ethernet', duration: '12 min' },
      { title: 'Paquete IPv4', duration: '15 min' },
      { title: 'Segmento UDP y TCP', duration: '15 min' },
      { title: 'Payload y application layer', duration: '10 min' },
      { title: 'Hex view: leer bytes crudos', duration: '12 min' },
    ],
    tools: ['wireshark', 'tcpdump', 'xxd'],
  }),
  stub({
    id: '05-wireshark',
    number: '05',
    title: 'Wireshark',
    subtitle: 'Captura y análisis de paquetes',
    slug: 'wireshark',
    group: 'packets',
    difficulty: 'beginner',
    estimatedTime: '2 h',
    prerequisites: ['04-packets'],
    description:
      'Curso completo de Wireshark orientado a tráfico drone: filtros, streams, conversations, export objects y el laboratorio "Capture the Drone".',
    icon: 'Fish',
    outcomes: [
      'Aplicar capture y display filters',
      'Seguir streams TCP/UDP',
      'Usar statistics y protocol hierarchy',
      'Resolver el lab "Capture the Drone"',
    ],
    plannedLessons: [
      { title: 'Interfaces y captura', duration: '12 min' },
      { title: 'Capture filters vs display filters', duration: '15 min' },
      { title: 'Packet coloring y streams', duration: '12 min' },
      { title: 'Conversations y endpoints', duration: '12 min' },
      { title: 'Protocol hierarchy y statistics', duration: '10 min' },
      { title: 'Hex view y packet bytes', duration: '10 min' },
      { title: 'Lab: Capture the Drone', duration: '25 min' },
    ],
    tools: ['wireshark'],
  }),
  stub({
    id: '06-tcpdump',
    number: '06',
    title: 'tcpdump',
    subtitle: 'Captura en línea de comandos',
    slug: 'tcpdump',
    group: 'packets',
    difficulty: 'beginner',
    estimatedTime: '1 h',
    prerequisites: ['05-wireshark'],
    description:
      'Laboratorio interactivo de tcpdump: -i, -nn, host, port, -w, -r y la cadena tcpdump → pcap → Wireshark.',
    icon: 'Terminal',
    plannedLessons: [
      { title: 'Sintaxis básica: -i, -nn', duration: '10 min' },
      { title: 'Filtros BPF: host, port, tcp, udp', duration: '15 min' },
      { title: 'Guardar y leer pcaps', duration: '10 min' },
      { title: 'Lab: capturar telemetría drone', duration: '20 min' },
    ],
    tools: ['tcpdump', 'wireshark'],
  }),
  stub({
    id: '07-wifi',
    number: '07',
    title: 'Wi-Fi Security',
    subtitle: '802.11 en sistemas drone',
    slug: 'wifi',
    group: 'wireless',
    difficulty: 'intermediate',
    estimatedTime: '3 h',
    prerequisites: ['02-networking'],
    description:
      'Curso completo de 802.11 aplicado a drones: management/control/data frames, WPA2/WPA3, PMF y el "Virtual Drone Wi-Fi Lab" aislado.',
    icon: 'Wifi',
    plannedLessons: [
      { title: 'Arquitectura 802.11', duration: '15 min' },
      { title: 'Frames: management, control, data', duration: '15 min' },
      { title: 'Auth y association', duration: '15 min' },
      { title: 'WPA2: handshake de 4 vías', duration: '20 min' },
      { title: 'WPA3 y SAE', duration: '15 min' },
      { title: 'PMF (802.11w)', duration: '12 min' },
      { title: 'aircrack-ng suite', duration: '20 min' },
      { title: 'Lab: Virtual Drone Wi-Fi Lab', duration: '30 min' },
    ],
    tools: ['aircrack-ng', 'iw', 'ip'],
  }),
  stub({
    id: '08-discovery',
    number: '08',
    title: 'Drone Discovery',
    subtitle: 'Reconocimiento y enumeración',
    slug: 'discovery',
    group: 'discovery',
    difficulty: 'intermediate',
    estimatedTime: '2 h',
    prerequisites: ['01-linux', '02-networking'],
    description:
      'Laboratorio simulado para encontrar el drone en la red, identificar sus servicios y mapear su superficie. Incluye el lab "Find the Drone".',
    icon: 'Radar',
    plannedLessons: [
      { title: 'Recon pasivo vs activo', duration: '12 min' },
      { title: 'nmap: host discovery', duration: '15 min' },
      { title: 'nmap: port y version scan', duration: '15 min' },
      { title: 'netcat para banner grabbing', duration: '12 min' },
      { title: 'Lab: Find the Drone', duration: '30 min' },
    ],
    tools: ['nmap', 'netcat', 'curl'],
  }),
  stub({
    id: '09-endpoints',
    number: '09',
    title: 'Endpoints',
    subtitle: 'HTTP, UDP, WebSocket, MAVLink',
    slug: 'endpoints',
    group: 'discovery',
    difficulty: 'intermediate',
    estimatedTime: '1.5 h',
    prerequisites: ['08-discovery'],
    description:
      'Qué es un endpoint, los tipos relevantes para drones y cómo se diseña uno seguro. Ejemplos REST, UDP sockets y endpoints MAVLink.',
    icon: 'Plug',
    plannedLessons: [
      { title: 'Tipos de endpoint', duration: '12 min' },
      { title: 'HTTP/REST endpoints', duration: '15 min' },
      { title: 'UDP y TCP sockets', duration: '12 min' },
      { title: 'WebSocket endpoints', duration: '12 min' },
      { title: 'MAVLink endpoints', duration: '15 min' },
      { title: 'Diseño seguro de endpoints', duration: '15 min' },
    ],
    tools: ['curl', 'netcat'],
  }),
  stub({
    id: '10-api-security',
    number: '10',
    title: 'API Security',
    subtitle: 'APIs vulnerables de drones',
    slug: 'api-security',
    group: 'discovery',
    difficulty: 'intermediate',
    estimatedTime: '3 h',
    prerequisites: ['09-endpoints'],
    description:
      'Auth, JWT, RBAC, IDOR, SSRF, inyección y más, sobre una drone API deliberadamente vulnerable en sandbox.',
    icon: 'Webhook',
    plannedLessons: [
      { title: 'AuthN vs AuthZ', duration: '15 min' },
      { title: 'JWT a fondo', duration: '20 min' },
      { title: 'API keys y sesiones', duration: '12 min' },
      { title: 'RBAC y IDOR/BOLA', duration: '20 min' },
      { title: 'Command injection en APIs', duration: '15 min' },
      { title: 'SSRF en APIs drone', duration: '15 min' },
      { title: 'Rate limiting y validación', duration: '12 min' },
      { title: 'Lab: vulnerable drone API', duration: '40 min' },
    ],
    tools: ['curl', 'burpsuite', 'jq'],
  }),
  stub({
    id: '11-request-capture',
    number: '11',
    title: 'Request Capture',
    subtitle: 'Observar peticiones de apps',
    slug: 'request-capture',
    group: 'request',
    difficulty: 'intermediate',
    estimatedTime: '2 h',
    prerequisites: ['10-api-security'],
    description:
      'Cómo interceptar el tráfico que genera una Drone Control App: Burp, mitmproxy y captura de login/status/telemetry/config.',
    icon: 'Filter',
    plannedLessons: [
      { title: 'Anatomía HTTP request/response', duration: '15 min' },
      { title: 'Headers, cookies, tokens', duration: '15 min' },
      { title: 'Burp Suite basics', duration: '20 min' },
      { title: 'mitmproxy', duration: '15 min' },
      { title: 'Lab: capturar Drone Control App', duration: '30 min' },
    ],
    tools: ['burpsuite', 'mitmproxy', 'wireshark'],
  }),
  stub({
    id: '12-request-replay',
    number: '12',
    title: 'Request Replay & Simulation',
    subtitle: 'Capturar, modificar, reenviar',
    slug: 'request-replay',
    group: 'request',
    difficulty: 'intermediate',
    estimatedTime: '2 h',
    prerequisites: ['11-request-capture'],
    description:
      'Simulador visual de replay: captura una petición, modifícala en el sandbox, reenvíala y compara la respuesta.',
    icon: 'Repeat',
    plannedLessons: [
      { title: 'Workflow del replay', duration: '12 min' },
      { title: 'Inspector de requests', duration: '15 min' },
      { title: 'Modificación segura en sandbox', duration: '15 min' },
      { title: 'Lab: replay de lab-command', duration: '30 min' },
    ],
    tools: ['burpsuite', 'curl'],
  }),
  stub({
    id: '13-mavlink',
    number: '13',
    title: 'MAVLink / Telemetry',
    subtitle: 'Protocolo binario de UAVs',
    slug: 'mavlink',
    group: 'drone-protocol',
    difficulty: 'advanced',
    estimatedTime: '3 h',
    prerequisites: ['04-packets', '03-drone-architecture'],
    description:
      'Introducción profunda a MAVLink: messages, IDs, system/component ID, heartbeat, telemetry y generación de mensajes sintéticos para el simulador.',
    icon: 'Radio',
    plannedLessons: [
      { title: 'Historia y versiones de MAVLink', duration: '12 min' },
      { title: 'Estructura del mensaje', duration: '20 min' },
      { title: 'System ID y Component ID', duration: '15 min' },
      { title: 'HEARTBEAT y secuencia', duration: '15 min' },
      { title: 'Mensajes comunes de telemetría', duration: '20 min' },
      { title: 'CRC y (falta de) seguridad', duration: '15 min' },
      { title: 'Lab: generar mensajes sintéticos', duration: '30 min' },
    ],
    tools: ['netcat', 'wireshark'],
  }),
  stub({
    id: '14-drone-simulator',
    number: '14',
    title: 'Drone Simulator',
    subtitle: 'Drone virtual con física simple',
    slug: 'drone-simulator',
    group: 'drone-protocol',
    difficulty: 'intermediate',
    estimatedTime: '2.5 h',
    prerequisites: ['13-mavlink'],
    description:
      'El drone virtual del laboratorio: posición, altitud, batería, GPS, modo, armado, telemetría y una física simple X/Y/Z con takeoff/land/move/hover.',
    icon: 'Plane',
    plannedLessons: [
      { title: 'Estado del drone', duration: '15 min' },
      { title: 'Física simple X/Y/Z', duration: '15 min' },
      { title: 'Modos de vuelo', duration: '15 min' },
      { title: 'Panel de control', duration: '20 min' },
      { title: 'Telemetría en vivo', duration: '15 min' },
      { title: 'Lab: pilotar el simulador', duration: '30 min' },
    ],
    tools: ['curl'],
  }),
  stub({
    id: '15-attack-labs',
    number: '15',
    title: 'Attack Labs',
    subtitle: 'CTF ofensivo guiado',
    slug: 'attack-labs',
    group: 'offensive',
    difficulty: 'advanced',
    estimatedTime: '6 h',
    prerequisites: ['05-wireshark', '08-discovery', '10-api-security'],
    description:
      'Diez laboratorios tipo CTF, cada uno con objetivo, contexto, recon, clues, tools, hints, flag, solución y mitigación.',
    icon: 'Crosshair',
    plannedLessons: [
      { title: 'Cómo funciona un Attack Lab', duration: '10 min' },
      { title: 'LAB 01: Find the Drone', duration: '30 min' },
      { title: 'LAB 03: Capture the Telemetry', duration: '30 min' },
      { title: 'LAB 05: Authorization Bug', duration: '40 min' },
      { title: 'LAB 07: Replay Synthetic Message', duration: '40 min' },
      { title: 'LAB 10: Harden the Drone', duration: '40 min' },
    ],
    tools: ['nmap', 'wireshark', 'curl', 'aircrack-ng'],
  }),
  stub({
    id: '16-companion-computer',
    number: '16',
    title: 'Companion Computer',
    subtitle: 'Linux embebido a bordo',
    slug: 'companion-computer',
    group: 'offensive',
    difficulty: 'advanced',
    estimatedTime: '2.5 h',
    prerequisites: ['01-linux'],
    description:
      'El Linux a bordo del drone: servicios, SSH, filesystem, procesos, GPIO/USB/serial y hardening.',
    icon: 'Cpu',
    plannedLessons: [
      { title: 'Arquitectura típica de un companion', duration: '15 min' },
      { title: 'Servicios y puertos', duration: '15 min' },
      { title: 'SSH y credenciales', duration: '15 min' },
      { title: 'Filesystem y configuración', duration: '20 min' },
      { title: 'GPIO, USB, serial', duration: '15 min' },
      { title: 'Lab: enumerar companion', duration: '30 min' },
      { title: 'Hardening', duration: '20 min' },
    ],
    tools: ['nmap', 'ip', 'ss'],
  }),
  stub({
    id: '17-firmware',
    number: '17',
    title: 'Firmware Analysis',
    subtitle: 'Diseccionar imágenes embebidas',
    slug: 'firmware',
    group: 'offensive',
    difficulty: 'advanced',
    estimatedTime: '3 h',
    prerequisites: ['16-companion-computer'],
    description:
      'Análisis de firmware: filesystem images, ELF, strings, secrets, mecanismos de update. Con imágenes deliberadamente vulnerables.',
    icon: 'Package',
    plannedLessons: [
      { title: 'Anatomía de un firmware', duration: '15 min' },
      { title: 'binwalk: escaneo y extracción', duration: '20 min' },
      { title: 'file, strings, xxd', duration: '15 min' },
      { title: 'Filesystems squashfs/jffs2', duration: '15 min' },
      { title: 'Secretos y credenciales', duration: '20 min' },
      { title: 'Update mechanisms', duration: '15 min' },
      { title: 'Lab: firmware vulnerable', duration: '40 min' },
    ],
    tools: ['binwalk', 'strings', 'xxd'],
  }),
  stub({
    id: '18-reverse-engineering',
    number: '18',
    title: 'Reverse Engineering',
    subtitle: 'ELF, asm y decompilación',
    slug: 'reverse-engineering',
    group: 'offensive',
    difficulty: 'expert',
    estimatedTime: '4 h',
    prerequisites: ['17-firmware'],
    description:
      'Introducción a RE con Ghidra y radare2 sobre binarios educativos del laboratorio: ELF, funciones, símbolos, control flow.',
    icon: 'Binary',
    plannedLessons: [
      { title: 'Formato ELF', duration: '20 min' },
      { title: 'Secciones y símbolos', duration: '15 min' },
      { title: 'Assembly básico x86/ARM', duration: '25 min' },
      { title: 'Ghidra: importar y analizar', duration: '20 min' },
      { title: 'radare2 en CLI', duration: '20 min' },
      { title: 'objdump y readelf', duration: '15 min' },
      { title: 'Lab: revertir un binario', duration: '45 min' },
    ],
    tools: ['ghidra', 'radare2', 'objdump', 'readelf'],
  }),
  stub({
    id: '19-fuzzing',
    number: '19',
    title: 'Fuzzing',
    subtitle: 'Romper servicios con input aleatorio',
    slug: 'fuzzing',
    group: 'offensive',
    difficulty: 'expert',
    estimatedTime: '3 h',
    prerequisites: ['18-reverse-engineering'],
    description:
      'Fuzzing mutacional y generation-based sobre un servicio UDP/TCP de laboratorio deliberadamente vulnerable.',
    icon: 'Bomb',
    plannedLessons: [
      { title: 'Qué es fuzzing', duration: '15 min' },
      { title: 'Mutational vs generation-based', duration: '15 min' },
      { title: 'Cobertura y crashes', duration: '15 min' },
      { title: 'Lab: fuzzear un servicio drone', duration: '45 min' },
    ],
    tools: ['radare2'],
  }),
  stub({
    id: '20-forensics',
    number: '20',
    title: 'Drone Forensics',
    subtitle: 'Investigar incidentes UAV',
    slug: 'forensics',
    group: 'defensive',
    difficulty: 'advanced',
    estimatedTime: '3 h',
    prerequisites: ['16-companion-computer'],
    description:
      'Análisis forense de flight logs, telemetría, filesystem, timestamps y GPS. Casos ficticios: "Drone recovered after incident".',
    icon: 'Search',
    plannedLessons: [
      { title: 'Metodología forense', duration: '15 min' },
      { title: 'Flight logs y .tlog', duration: '20 min' },
      { title: 'Filesystem del companion', duration: '20 min' },
      { title: 'Metadata y timestamps', duration: '15 min' },
      { title: 'GPS data', duration: '15 min' },
      { title: 'Lab: drone recovered', duration: '45 min' },
    ],
    tools: ['strings', 'xxd'],
  }),
  stub({
    id: '21-threat-modeling',
    number: '21',
    title: 'Threat Modeling',
    subtitle: 'STRIDE para UAVs',
    slug: 'threat-modeling',
    group: 'defensive',
    difficulty: 'intermediate',
    estimatedTime: '2 h',
    prerequisites: ['00-start-here'],
    description:
      'STRIDE, attack surface, assets, attack vectors, trust boundaries y attack trees. Construye un threat model visual del drone.',
    icon: 'Network',
    plannedLessons: [
      { title: 'STRIDE en detalle', duration: '20 min' },
      { title: 'Attack trees', duration: '15 min' },
      { title: 'Trust boundaries', duration: '15 min' },
      { title: 'Lab: threat model visual', duration: '40 min' },
    ],
    tools: [],
  }),
  stub({
    id: '22-defensive',
    number: '22',
    title: 'Defensive Security',
    subtitle: 'Hardening de drones',
    slug: 'defensive',
    group: 'defensive',
    difficulty: 'advanced',
    estimatedTime: '3 h',
    prerequisites: ['10-api-security', '13-mavlink'],
    description:
      'Para cada vulnerabilidad: explain → exploit → detect → mitigate → verify. Secure boot, firmware signing, segmentation, IDS, key management.',
    icon: 'ShieldCheck',
    plannedLessons: [
      { title: 'Ciclo EXPLAIN→EXPLOIT→DETECT→MITIGATE→VERIFY', duration: '15 min' },
      { title: 'Secure authentication', duration: '20 min' },
      { title: 'Cifrado y MAC de mensajes', duration: '20 min' },
      { title: 'Secure boot y firmware signing', duration: '20 min' },
      { title: 'Segmentación y firewalling', duration: '15 min' },
      { title: 'Logging, IDS, monitoring', duration: '20 min' },
      { title: 'Key management', duration: '15 min' },
    ],
    tools: [],
  }),
  stub({
    id: '23-incident-response',
    number: '23',
    title: 'Incident Response',
    subtitle: 'Responder a incidentes UAV',
    slug: 'incident-response',
    group: 'defensive',
    difficulty: 'advanced',
    estimatedTime: '2 h',
    prerequisites: ['20-forensics'],
    description:
      'Escenarios: unauthorized telemetry, suspicious API requests, unknown device, firmware tampering, compromised companion. Investigación con logs y pcaps.',
    icon: 'Siren',
    plannedLessons: [
      { title: 'IR lifecycle para UAVs', duration: '15 min' },
      { title: 'Caso: unauthorized telemetry', duration: '25 min' },
      { title: 'Caso: suspicious API requests', duration: '25 min' },
      { title: 'Caso: firmware tampering', duration: '25 min' },
    ],
    tools: ['wireshark', 'tcpdump'],
  }),
  stub({
    id: '24-ctf',
    number: '24',
    title: 'CTF Mode',
    subtitle: 'Modo competitivo',
    slug: 'ctf',
    group: 'meta',
    difficulty: 'advanced',
    estimatedTime: '∞',
    prerequisites: ['15-attack-labs'],
    description:
      'Modo competitivo: flags, puntos, tiempo, dificultad, leaderboard local y achievements. Categorías: network, wireless, web, API, embedded, forensics, RE, drone protocols.',
    icon: 'Trophy',
    plannedLessons: [
      { title: 'Cómo funciona el CTF', duration: '10 min' },
      { title: 'Categorías y puntuación', duration: '10 min' },
      { title: 'Leaderboard y achievements', duration: '10 min' },
    ],
    tools: [],
  }),
  stub({
    id: '25-toolbox',
    number: '25',
    title: 'Toolbox',
    subtitle: 'Catálogo de herramientas',
    slug: 'toolbox',
    group: 'meta',
    difficulty: 'beginner',
    estimatedTime: '1 h',
    prerequisites: [],
    description:
      'Referencia rápida de cada herramienta: qué hace, comandos clave, errores comunes y lab asociado.',
    icon: 'Wrench',
    plannedLessons: [],
    tools: ['wireshark', 'nmap', 'aircrack-ng', 'ghidra'],
  }),
  stub({
    id: '26-glossary',
    number: '26',
    title: 'Glossary',
    subtitle: 'Diccionario interactivo',
    slug: 'glossary',
    group: 'meta',
    difficulty: 'beginner',
    estimatedTime: '0.5 h',
    prerequisites: [],
    description:
      'Diccionario de términos de drone cybersecurity: UAV, MAVLink, BSSID, PMF, RTSP y más. Cada término con definición, relevancia y ejemplo.',
    icon: 'BookA',
    plannedLessons: [],
    tools: [],
  }),
  stub({
    id: '27-learning-path',
    number: '27',
    title: 'Learning Path',
    subtitle: 'Rutas por rol',
    slug: 'learning-path',
    group: 'meta',
    difficulty: 'beginner',
    estimatedTime: '0.5 h',
    prerequisites: [],
    description:
      'Rutas guiadas: Beginner, Intermediate, Advanced, Red Team, Blue Team, Researcher.',
    icon: 'Route',
    plannedLessons: [],
    tools: [],
  }),
]
